[project]
name = "ccvj"
version = "0.1.0"
description = "CreativeCommons Vietnamese Journals Dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp",
    "certifi",
    "diskcache",
    "loguru",
    "requests",
    "sickle",
    "typer",
]
